// Wording matches the app's storefront (frontend/lib/l10n, `store*` keys) so
// a customer moving from the app to the site reads the same labels.
export const storeStrings = {
  ar: {
    title: 'متجر SportXHub',
    lead: 'تسوق حسب القسم. كل قسم فيه ملابس وأحذية رياضية وأدوات رياضية.',
    shopByCategory: 'تسوّق حسب القسم',
    featured: 'منتجات مختارة',
    newArrivals: 'وصل حديثاً',
    viewAll: 'عرض الكل',
    allProducts: 'كل المنتجات',
    allIn: 'كل',
    shop: 'تسوّق',
    search: 'ابحث عن منتج',
    cart: 'السلة',
    track: 'تتبّع طلبك',
    sortNewest: 'الأحدث',
    sortPriceAsc: 'السعر: من الأقل',
    sortPriceDesc: 'السعر: من الأعلى',
    noProducts: 'لا توجد منتجات مطابقة.',
    loadMore: 'عرض منتجات أكتر',
    badge: { new: 'جديد', pre_order: 'طلب مسبق', sale: 'تخفيض' },
    soldOut: 'نفدت الكمية',
    selectSize: 'اختر المقاس',
    selectColour: 'اختر اللون',
    size: 'المقاس',
    colour: 'اللون',
    addToBag: 'أضف إلى السلة',
    addedToBag: 'تمت الإضافة إلى السلة',
    viewBag: 'عرض السلة',
    quantity: 'الكمية',
    remove: 'إزالة',
    cartEmpty: 'سلتك فارغة.',
    continueShopping: 'تابع التسوّق',
    checkout: 'إتمام الطلب',
    shippingAtCheckout: 'يُحسب الشحن حسب المحافظة',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    shippingFee: 'الشحن',
    total: 'الإجمالي',
    couponLabel: 'كود الخصم',
    couponApply: 'تطبيق',
    couponApplied: 'تم تطبيق الكود',
    couponRemove: 'إزالة الكود',
    checkoutTitle: 'بيانات الشحن',
    fullName: 'الاسم بالكامل',
    phone: 'رقم الموبايل',
    email: 'البريد الإلكتروني',
    governorate: 'المحافظة',
    chooseGovernorate: 'اختار المحافظة',
    city: 'المدينة / المنطقة',
    street: 'العنوان بالتفصيل',
    notes: 'ملاحظات للتوصيل (اختياري)',
    payment: 'طريقة الدفع',
    cod: 'الدفع عند الاستلام',
    placeOrder: 'تأكيد الطلب',
    placing: 'جاري إرسال الطلب…',
    required: 'هذا الحقل مطلوب',
    invalidPhone: 'أدخل رقم موبايل مصري صحيح',
    invalidEmail: 'أدخل بريداً إلكترونياً صحيحاً',
    orderPlaced: 'تم استلام طلبك',
    orderNumberIs: 'رقم طلبك',
    keepNumber: 'احتفظ برقم الطلب — هتحتاجه أنت وبريدك الإلكتروني عشان تتابع الطلب.',
    trackTitle: 'تتبّع طلبك',
    trackLead: 'اكتب رقم الطلب والإيميل اللي طلبت بيه.',
    orderNumber: 'رقم الطلب',
    trackSubmit: 'عرض الطلب',
    orderNotFound: 'لم نعثر على طلب بهذا الرقم والبريد الإلكتروني.',
    status: {
      pending: 'قيد المراجعة',
      confirmed: 'تم التأكيد',
      shipped: 'تم الشحن',
      delivered: 'تم التسليم',
      cancelled: 'ملغي',
    },
    deliverTo: 'التوصيل إلى',
    items: 'المنتجات',
    error: 'حصلت مشكلة. اتأكد من الإنترنت وجرب تاني.',
    notFound: 'المنتج ده مش موجود أو اتشال من المتجر.',
    backToStore: 'العودة للمتجر',
    perks: ['شحن لكل المحافظات', 'الدفع عند الاستلام', 'إرجاع خلال ١٤ يوم'],
    unavailable: 'المنتج ده مش متاح دلوقتي واتشال من سلتك.',
  },
  en: {
    title: 'SportXHub Store',
    lead: 'Shop by department. Each one has clothing, shoes and sports equipment.',
    shopByCategory: 'Shop by category',
    featured: 'Featured',
    newArrivals: 'New arrivals',
    viewAll: 'View all',
    allProducts: 'All products',
    allIn: 'All',
    shop: 'Shop',
    search: 'Search products',
    cart: 'Bag',
    track: 'Track your order',
    sortNewest: 'Newest',
    sortPriceAsc: 'Price: low to high',
    sortPriceDesc: 'Price: high to low',
    noProducts: 'No products match that.',
    loadMore: 'Show more products',
    badge: { new: 'New', pre_order: 'Pre-order', sale: 'Sale' },
    soldOut: 'Sold out',
    selectSize: 'Select a size',
    selectColour: 'Select a colour',
    size: 'Size',
    colour: 'Colour',
    addToBag: 'Add to bag',
    addedToBag: 'Added to your bag',
    viewBag: 'View bag',
    quantity: 'Quantity',
    remove: 'Remove',
    cartEmpty: 'Your bag is empty.',
    continueShopping: 'Continue shopping',
    checkout: 'Checkout',
    shippingAtCheckout: 'Shipping is priced by governorate',
    subtotal: 'Subtotal',
    discount: 'Discount',
    shippingFee: 'Shipping',
    total: 'Total',
    couponLabel: 'Discount code',
    couponApply: 'Apply',
    couponApplied: 'Code applied',
    couponRemove: 'Remove code',
    checkoutTitle: 'Delivery details',
    fullName: 'Full name',
    phone: 'Mobile number',
    email: 'Email',
    governorate: 'Governorate',
    chooseGovernorate: 'Choose a governorate',
    city: 'City / area',
    street: 'Street address',
    notes: 'Delivery notes (optional)',
    payment: 'Payment',
    cod: 'Cash on delivery',
    placeOrder: 'Place order',
    placing: 'Placing your order…',
    required: 'This field is required',
    invalidPhone: 'Enter a valid Egyptian mobile number',
    invalidEmail: 'Enter a valid email address',
    orderPlaced: 'Order received',
    orderNumberIs: 'Your order number',
    keepNumber: 'Keep this number — you will need it and your email to track the order.',
    trackTitle: 'Track your order',
    trackLead: 'Enter your order number and the email you ordered with.',
    orderNumber: 'Order number',
    trackSubmit: 'View order',
    orderNotFound: 'No order matches that number and email.',
    status: {
      pending: 'Pending',
      confirmed: 'Confirmed',
      shipped: 'Shipped',
      delivered: 'Delivered',
      cancelled: 'Cancelled',
    },
    deliverTo: 'Delivering to',
    items: 'Items',
    error: 'Something went wrong. Check your connection and try again.',
    notFound: 'This product does not exist or was removed from the store.',
    backToStore: 'Back to the store',
    perks: ['Delivery to every governorate', 'Cash on delivery', '14-day returns'],
    unavailable: 'This product is no longer available and was removed from your bag.',
  },
} as const;

export type StoreDict = (typeof storeStrings)['ar' | 'en'];
